### ISSUE TITLE
No subfolder 'emhass' in /share/ when saving outside of the default-folder

### ISSUE THREAD

**Issue by RudolfRendier** [davidusb-geek/emhass-add-on#106]
When opting to save files into /share/ there's no emhass subfolder (as indicated by the explanation)

The description below it does mention such a folder:
"data_path (Default default), selecting /data/ will store data in an enclosed folder, only assessable by the addon itself. Select /share/emhass to store data in the mounted share folder, accessible outside of the addon"

Adapting the yaml to /share/emhass is not accepted.

A few other add-ons saving data there all save it in a subfolder with their own name.

**Comment by davidusb-geek** [comment]
Hi, yes the files are just saved directly into the `share` folder.
We probably just need to update that description

**Comment by davidusb-geek** [comment]
I've just modified this message.
Closing this issue
