### ISSUE TITLE
v0.11.4: failed to install add-on

### ISSUE THREAD

**Issue by heinemannj** [davidusb-geek/emhass-add-on#108]
![image](https://github.com/user-attachments/assets/8fab73dc-9709-4313-b81a-f5a09a778d2b)

**Comment by heinemannj** [comment]
Switching back to v0.11.2 because v0.11.3 makes a lot of trouble

**Comment by davidusb-geek** [comment]
Please try again now, it worked fine for me.
Sometimes it takes just some more minutes for the docker images to get generated. It will take some more minutes if your HA instance is on a Raspberry Pi

![image](https://github.com/user-attachments/assets/056a9766-1c42-4688-b189-fe325d5d64e3)

**Comment by heinemannj** [comment]
Jepp - working now as expected - also the previous issues produced by v0.11.3 are fixed.
Many thanks.

Cheers
Joerg
