### ISSUE TITLE
Typo in the graphs

### ISSUE THREAD

**Issue by RalfPfitzner** [davidusb-geek/emhass-add-on#27]
Hi David,
there is a typo in the graphs. Nothing to worry about but you might change... Timestamp instead of Tiemstamp

Both graphs affected :-)

![image](https://user-images.githubusercontent.com/58477798/189826018-a7154033-bbc4-4fc7-a65d-9e6e6ee4afc2.png)

**Comment by davidusb-geek** [comment]
Yes, thank you for reporting this. I've just fixed it on https://github.com/davidusb-geek/emhass@16b8edb
