### ISSUE TITLE
Using comma separated values in the configuration do not work

### ISSUE THREAD

**Issue by overas** [davidusb-geek/emhass-add-on#30]
I am using emhass version 0.2.22 addon.

In the configuration I have this config:
![image](https://user-images.githubusercontent.com/37910044/196003916-d273ff69-0b24-4e83-a24c-f30ebf868208.png)

Under the form the help text says:
_This is a list of comma separated values with a number of elements consistent with the number of deferrable loads defined before. For example 3000, 750_
and
_A list of comma separated values. For example 5, 8_

I try to change the config to use comma separated values:
![image](https://user-images.githubusercontent.com/37910044/196004032-bf292bd8-5d73-4a2d-96bb-2cc811fba5f3.png)

I then get this error when trying to save:
![image](https://user-images.githubusercontent.com/37910044/196004093-80956f95-7659-4683-9768-bb31af611234.png)

**Comment by davidusb-geek** [comment]
Oh yes this is misleading, thank you for reporting this. That information is actually accurate just when using the core emhass python module, not for the add-on. I'll fix this information. In the add-on you just have to provide a list as shown on the top of your post, and not comma separated values

**Comment by davidusb-geek** [comment]
Done! 👍
