### ISSUE TITLE
no valid repository 

### ISSUE THREAD

**Issue by farshadnl** [davidusb-geek/emhass-add-on#42]
Hello ,

i tried to add the emhass repository to my HA but it failed with error: No valid repository 
https://github.com/davidusb-geek/emhass.git
Please can you help with this issue?

Many thanks

**Comment by farshadnl** [comment]
![image](https://user-images.githubusercontent.com/120740798/230629814-46a1b4dc-f143-4dd2-8342-9b024bebcac5.png)

**Comment by davidusb-geek** [comment]
You are not using the correct repository.

Use this: https://github.com/davidusb-geek/emhass-add-on.git

**Comment by farshadnl** [comment]
Many Thanks.

**Comment by cloudbr34k84** [comment]
> You are not using the correct repository.
> 
> Use this: https://github.com/davidusb-geek/emhass-add-on.git

Im trying that link and it's not working as well
https://github.com/davidusb-geek/emhass-add-on.git
![Screenshot_20230724-035734](https://github.com/davidusb-geek/emhass-add-on/assets/58960644/8cc8e33e-abf0-47ca-aa34-118006c1a50f)

**Comment by davidusb-geek** [comment]
Your error message links to emhass.git which like said is not the correct repository, the correct will be emhass-add-on.git. You can try restarting Home Assistant and retry adding the repository
