### ISSUE TITLE
 - operating_hours_of_each_deferrable_load: depends on optimization_time_step

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass-add-on#5]
- operating_hours_of_each_deferrable_load: 8

Actually only runs for 8 hours if the optimization_time_step is set to 60 minutes

If optimization_time_step is 30 minutes, setting operating_hours variable to 8 only schedules 8 x 30 min blocks, ie four hours.

**Comment by davidusb-geek** [comment]
Hi, thank you for this observation. Just fixed this and added a correct unittest to automatically test this in the core emhass module.
Update to >> v0.1.42
