### ISSUE TITLE
Cannot add repository in addon store 

### ISSUE THREAD

**Issue by pwwukpw** [davidusb-geek/emhass-add-on#60]
Getting this error .  

Any advice appreciated 
![Screenshot_20231126_072417_Home Assistant](https://github.com/davidusb-geek/emhass-add-on/assets/88422402/24e4f4f7-604a-4be4-abd1-2c7fea7b93a6)

**Comment by davidusb-geek** [comment]
You have the wrong url.
This is the correct url which is the same as this repository where you opened this issue:

https://github.com/davidusb-geek/emhass-add-on

It is curious how from time to time there is this confusion. May be it is the documentation creating this confusion?
