### ISSUE TITLE
Publish failed for 0.5.1

### ISSUE THREAD

**Issue by wilfredktlr** [davidusb-geek/emhass-add-on#62]
I cannot update to 0.5.1 because https://github.com/davidusb-geek/emhass-add-on/actions/runs/7240845918 has failed.

**Comment by davidusb-geek** [comment]
it should be solved, upgrade to add-on v0.5.2 when it is available.
Please close the issue if everything goes back to normal

**Comment by wilfredktlr** [comment]
It is working again.
