### ISSUE TITLE
Emhass Fails to install

### ISSUE THREAD

**Issue by Samuel12321** [davidusb-geek/emhass-add-on#63]
Tring to install EMHASS through HAOS produces the following error message:
![Screenshot 2023-12-18 115851](https://github.com/davidusb-geek/emhass-add-on/assets/35312698/54b9891f-34bd-4e2d-b5c0-aa5cea70ffef)

**Comment by davidusb-geek** [comment]
it should be solved, upgrade to add-on v0.5.2 when it is available.
Please close the issue if everything goes back to normal

**Comment by Samuel12321** [comment]
Fixed
