### ISSUE TITLE
Dynamic Pricing

### ISSUE THREAD

**Issue by deece** [davidusb-geek/emhass-add-on#64]
I use Amber Electric ( https://www.amber.com.au/ ) which provides electricity at (approximately) the wholesale spot price.

They have an API, and I am already exposing the import and export prices to Home Assistant via a currency sensor.

It would be great to support this pricing model in addition to flat rate or time of use pricing.

**Comment by davidusb-geek** [comment]
This is totally supported, you can pass those dynamic values to the add-on as list of values. Read the documentation for examples on how to do this. There are people using Amber and EMHASS, you can ask for help to set it up on the HomeAssistant forum.

**Comment by deece** [comment]
Thanks!
