### ISSUE TITLE
Make use of variable electrical price

### ISSUE THREAD

**Issue by Gompman** [davidusb-geek/emhass-add-on#66]
I have an electricity contract that updates the exchange prices every hour (https://tibber.com/de). I can see the prices for the next 24 hours via api. 

is it possible to use/consider this type of electrical cost?

**Comment by davidusb-geek** [comment]
Of course, 100% supported, you can pass those dynamic values to the add-on as a list of values. Read the documentation for examples on how to do this. There are people using Tibber and EMHASS, you can ask for help to set it up on the HomeAssistant forum.
