### ISSUE TITLE
Emhass Addon fails to install

### ISSUE THREAD

**Issue by christianmeder** [davidusb-geek/emhass-add-on#99]
The addon fails to install with manifest unknown.

![Screenshot 2024-07-12 18 26 34](https://github.com/user-attachments/assets/51284536-7665-4cfb-b4a8-6ca07871ba40)

**Comment by davidusb-geek** [comment]
Yes, build for ARM architectures are failiing and I don't know why. It seems like a github timeout problem.
I need to investigate this

**Comment by nicolas-sora** [comment]
Same issue for me except it asks to check supervisor logs which show nothing..

**Comment by davidusb-geek** [comment]
This should be solved.
Closing
